$('.man-carysel').slick({
    dots:true,
    arrows:false
});
$('.biography-carousel').slick({
    dots:true,
    arrows:false
});
$('.news-carusel').slick({
    dots:true,
    vertical:true,
    arrows:false
});